# Generated by Django 4.1.6 on 2023-02-12 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initiative', models.IntegerField()),
                ('can_install', models.BooleanField(default=False)),
                ('installation_charges', models.IntegerField(default=1)),
                ('burn_after_install', models.BooleanField(default=False)),
                ('level', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='cards/')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('retired', models.BooleanField(default=False)),
                ('notes', models.CharField(default='', max_length=2000)),
                ('gold', models.IntegerField(default=0)),
                ('wood', models.IntegerField(default=0)),
                ('iron', models.IntegerField(default=0)),
                ('leather', models.IntegerField(default=0)),
                ('arrowvine', models.IntegerField(default=0)),
                ('axenut', models.IntegerField(default=0)),
                ('corpsecap', models.IntegerField(default=0)),
                ('flamefruit', models.IntegerField(default=0)),
                ('rockroot', models.IntegerField(default=0)),
                ('snowthistle', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hand_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flip_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=500)),
                ('flip_description', models.CharField(blank=True, max_length=500, null=True)),
                ('slot', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='items/')),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='perks/')),
                ('active', models.BooleanField(default=False)),
                ('max_uses', models.IntegerField(default=1)),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.characterclass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.character')),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perk')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField()),
                ('ability_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.abilitycard')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.characterclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abilitycard',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.characterclass'),
        ),
    ]
