# Generated by Django 4.1.6 on 2023-02-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='flip_description',
            new_name='flipDescription',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='flip_name',
            new_name='flipName',
        ),
        migrations.AddField(
            model_name='item',
            name='flipTimer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='flippedFlipTimer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='flippedImage',
            field=models.ImageField(null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='flippedUses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isFlippable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='isPassive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='isReturnedOnLongRest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='upgradedFrom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='charactercard',
            constraint=models.UniqueConstraint(fields=('character', 'ability_card'), name='character - card'),
        ),
    ]
