# Generated by Django 4.1.6 on 2023-02-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteritems',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='flip_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='flip_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
