# Generated by Django 4.1.6 on 2023-02-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_characteritems_equipped_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterItems',
            new_name='CharacterItem',
        ),
    ]
