# Generated by Django 4.1.6 on 2023-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_charactercard_ability_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='flippedImage',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
