# Generated by Django 4.1.6 on 2023-02-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_characteritems_characteritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
