# Generated by Django 4.1.6 on 2023-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_flippedimage_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='perk_ticks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='arrowvine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='axenut',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='corpsecap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='flamefruit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='iron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='leather',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rockroot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='snowthistle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='wood',
            field=models.IntegerField(default=0),
        ),
    ]
