# Generated by Django 4.1.6 on 2023-02-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_character_perk_ticks_item_arrowvine_item_axenut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character_class',
            new_name='characterClass',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='perk_ticks',
            new_name='perkTicks',
        ),
    ]
