# Generated by Django 4.1.6 on 2023-02-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_character_arrowvine_character_axenut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitycard',
            name='image',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
    ]
