# Generated by Django 4.1.6 on 2023-02-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_characterperk_active_item_image_perk_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='character_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.characterclass'),
        ),
        migrations.AlterField(
            model_name='abilitycard',
            name='burn_after_install',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='abilitycard',
            name='can_install',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='abilitycard',
            name='installation_charges',
            field=models.IntegerField(null=True),
        ),
    ]
