# Generated by Django 4.1.6 on 2023-02-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_perk_character_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.characterclass'),
        ),
    ]
