# Generated by Django 4.1.6 on 2023-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_perk_character_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitycard',
            name='burn_after_install',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abilitycard',
            name='can_install',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abilitycard',
            name='installation_charges',
            field=models.IntegerField(default=1),
        ),
    ]
