# Generated by Django 4.1.6 on 2023-02-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_abilitycard_burn_after_install_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perk',
            name='description',
        ),
    ]
